package Vista;

import Controlador.ControladorReportes;
import Modelo.ModeloDetalleVenta;
import Modelo.ModeloReporteVentasPeriodo;
import Util.GeneradorPDF;
import Util.Mensajes;
import Util.TemaModerno;
import com.itextpdf.text.DocumentException;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

@SuppressWarnings("serial")
public class FrmReporteVentasPeriodo extends javax.swing.JInternalFrame {

    private ControladorReportes controlador;
    private DefaultTableModel modeloTabla;
    private ModeloReporteVentasPeriodo reporteActual;

    public FrmReporteVentasPeriodo() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.controlador = new ControladorReportes();
        this.modeloTabla = (DefaultTableModel) tbTotal.getModel();
        aplicarTemaModerno();
    }
    
    /**
     * Aplica el tema moderno a todos los componentes de la interfaz.
     */
    private void aplicarTemaModerno() {
        TemaModerno.estilizarBoton(btnBuscar, "primario");
        TemaModerno.estilizarBoton(btnGenerarPDF, "secundario");
        
        TemaModerno.estilizarTabla(tbTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtDesde = new com.toedter.calendar.JDateChooser();
        txtHasta = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTotal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnGenerarPDF = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Reporte de Ventas por Periodo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Por Fecha de Ventas"));

        jLabel1.setText("Desde:");

        jLabel2.setText("Hasta:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tbTotal.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {},new String [] {"ID Factura", "Fecha", "N.Producto", "Cantidad", "PrecioVenta", "Subtotal", "Total"}) {
            boolean[] canEdit = new boolean [] {false, false, false, false, false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTotal);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("INGRESOS TOTALES");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setText("....");

        btnGenerarPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.setEnabled(false);
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(50, 50, 50)
                .addComponent(btnGenerarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerarPDF)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Date fechaDesde = txtDesde.getDate();
        Date fechaHasta = txtHasta.getDate();

        if (fechaDesde == null || fechaHasta == null) {
            JOptionPane.showMessageDialog(this, Mensajes.MSG_SELECCIONE_RANGO_FECHAS, Mensajes.TITULO_ADVERTENCIA, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (fechaDesde.after(fechaHasta)) {
            JOptionPane.showMessageDialog(this, Mensajes.MSG_FECHAS_INCOHERENTES, Mensajes.TITULO_ADVERTENCIA, JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            ModeloReporteVentasPeriodo reporte = controlador.generarReportePorFecha(fechaDesde, fechaHasta);
            
            reporteActual = reporte;
            
            modeloTabla.setRowCount(0);
            
            for (ModeloDetalleVenta item : reporte.getItems()) {

                modeloTabla.addRow(new Object[]{
                    item.getIdFactura(),
                    item.getFechaFactura(),
                    item.getNombreProducto(),
                    item.getCantidad(),
                    item.getPrecioVenta(),
                    item.getSubtotal(),
                    String.format("%.2f", item.getTotal())
                });
            }
            
            lblTotal.setText(String.valueOf(reporte.getTotalIvaGeneral()));
            
            btnGenerarPDF.setEnabled(true);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, Mensajes.MSG_ERROR_BD + e.getMessage(), Mensajes.TITULO_ERROR, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {
        // Validación previa
        if (reporteActual == null) {
            JOptionPane.showMessageDialog(this,
                    Mensajes.MSG_REPORTE_REQUERIDO_PDF,
                    Mensajes.TITULO_ADVERTENCIA,
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String rutaPDF = GeneradorPDF.generarPDFReporteVentasPeriodo(reporteActual);
            int respuesta = JOptionPane.showConfirmDialog(this,
                    String.format(Mensajes.MSG_PDF_GENERADO_EXITO, rutaPDF),
                    Mensajes.TITULO_PDF_GENERADO,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                abrirArchivo(rutaPDF);
            }

        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(this,
                    Mensajes.MSG_ERROR_CREAR_PDF + e.getMessage(),
                    Mensajes.TITULO_ERROR,
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Abre un archivo con la aplicación predeterminada del sistema.
     * 
     * @param rutaArchivo La ruta del archivo a abrir
     */
    private void abrirArchivo(String rutaArchivo) {
        try {
            File archivo = new File(rutaArchivo);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(archivo);
            } else {
                JOptionPane.showMessageDialog(this,
                        Mensajes.MSG_ERROR_ABRIR_ARCHIVO + "\nUbicación: " + rutaArchivo,
                    "Información", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                "Error al abrir el archivo: " + e.getMessage(),
                    Mensajes.TITULO_ERROR,
                JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tbTotal;
    private com.toedter.calendar.JDateChooser txtDesde;
    private com.toedter.calendar.JDateChooser txtHasta;
    // End of variables declaration//GEN-END:variables
}

