package Vista;

import Controlador.ControladorReportes;
import Modelo.ModeloReporteFactura;
import Modelo.ModeloDetalleVenta;
import Util.Constantes;
import Util.GeneradorPDF;
import Util.Mensajes;
import Util.TemaModerno;
import com.itextpdf.text.DocumentException;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmReporteFactura extends javax.swing.JInternalFrame {

    private ControladorReportes controlador;
    private DefaultTableModel modeloTablaProductos;
    private ModeloReporteFactura reporteActual;

    public FrmReporteFactura() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.controlador = new ControladorReportes();
        this.modeloTablaProductos = (DefaultTableModel) tbProductos.getModel();
        
        aplicarTemaModerno();
    }
    
    /**
     * Aplica el tema moderno a todos los componentes de la interfaz.
     */
    private void aplicarTemaModerno() {
        TemaModerno.estilizarCampoTexto(txtBuscar);
        
        TemaModerno.estilizarBoton(btnBuscar, "primario");
        TemaModerno.estilizarBoton(btnGenerarPDF, "secundario");
        
        TemaModerno.estilizarTabla(tbProductos);
    }

    private void limpiarCampos() {
        lbMostrarFactura.setText("...");
        lbMostrarFechaDeVenta.setText("...");
        lbMostrarNombres.setText("...");
        lbMostrarApellidoPaterno.setText("...");
        lbMostrarApellidoMaterno.setText("...");
        lbMostrarIVA.setText("...");
        lbMostrarTotal.setText("...");
        modeloTablaProductos.setRowCount(0);
        reporteActual = null;
        btnGenerarPDF.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlIngresarNumeroDeFactura = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lbFactura = new javax.swing.JLabel();
        lbMostrarFactura = new javax.swing.JLabel();
        lbFechaDeVenta = new javax.swing.JLabel();
        lbMostrarFechaDeVenta = new javax.swing.JLabel();
        pnlDatosCliente = new javax.swing.JPanel();
        lbNombres = new javax.swing.JLabel();
        lbApellidoPaterno = new javax.swing.JLabel();
        lbApellidoMaterno = new javax.swing.JLabel();
        lbMostrarNombres = new javax.swing.JLabel();
        lbMostrarApellidoPaterno = new javax.swing.JLabel();
        lbMostrarApellidoMaterno = new javax.swing.JLabel();
        lbProductos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        lbIVA = new javax.swing.JLabel();
        lbMostrarIVA = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbMostrarTotal = new javax.swing.JLabel();
        btnGenerarPDF = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Reporte de Factura");

        pnlIngresarNumeroDeFactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Numero de Factura"));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIngresarNumeroDeFacturaLayout = new javax.swing.GroupLayout(pnlIngresarNumeroDeFactura);
        pnlIngresarNumeroDeFactura.setLayout(pnlIngresarNumeroDeFacturaLayout);
        pnlIngresarNumeroDeFacturaLayout.setHorizontalGroup(
                pnlIngresarNumeroDeFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlIngresarNumeroDeFacturaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIngresarNumeroDeFacturaLayout.setVerticalGroup(
                pnlIngresarNumeroDeFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlIngresarNumeroDeFacturaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlIngresarNumeroDeFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscar))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        lbFactura.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbFactura.setText("Factura N°:");
        lbMostrarFactura.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarFactura.setText("...");

        lbFechaDeVenta.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbFechaDeVenta.setText("Fecha de Venta:");
        lbMostrarFechaDeVenta.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarFechaDeVenta.setText("...");

        pnlDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));
        lbNombres.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbNombres.setText("Nombres:");
        lbApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbApellidoPaterno.setText("Ap.Paterno:");
        lbApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbApellidoMaterno.setText("Ap.Materno:");
        lbMostrarNombres.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarNombres.setText("...");
        lbMostrarApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarApellidoPaterno.setText("...");
        lbMostrarApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarApellidoMaterno.setText("...");

        javax.swing.GroupLayout pnlDatosClienteLayout = new javax.swing.GroupLayout(pnlDatosCliente);
        pnlDatosCliente.setLayout(pnlDatosClienteLayout);
        pnlDatosClienteLayout.setHorizontalGroup(
                pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNombres)
                                        .addComponent(lbMostrarNombres))
                                .addGap(57, 57, 57)
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbApellidoPaterno)
                                        .addComponent(lbMostrarApellidoPaterno))
                                .addGap(37, 37, 37)
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbMostrarApellidoMaterno)
                                        .addComponent(lbApellidoMaterno))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosClienteLayout.setVerticalGroup(
                pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbApellidoPaterno)
                                        .addComponent(lbNombres)
                                        .addComponent(lbApellidoMaterno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbMostrarApellidoPaterno)
                                        .addComponent(lbMostrarApellidoMaterno)
                                        .addComponent(lbMostrarNombres))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbProductos.setText("Productos");

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {}, new String [] {"N.Producto", "Cantidad", "PrecioVenta", "Subtotal"}) {
            boolean[] canEdit = new boolean [] {false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbProductos);

        lbIVA.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbIVA.setText("IVA:");
        lbMostrarIVA.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarIVA.setText("...");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lbTotal.setText("Total:");
        lbMostrarTotal.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lbMostrarTotal.setText("...");

        btnGenerarPDF.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.setEnabled(false);
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbProductos)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbFactura)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbMostrarFactura)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbFechaDeVenta)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbMostrarFechaDeVenta))
                                        .addComponent(pnlDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlIngresarNumeroDeFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)

                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE) 
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbIVA)
                                                        .addComponent(lbTotal))
                                                .addGap(15, 15, 15) 
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbMostrarIVA)
                                                        .addComponent(lbMostrarTotal))))
                                .addContainerGap(26, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(pnlIngresarNumeroDeFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbFactura)
                                        .addComponent(lbMostrarFactura)
                                        .addComponent(lbFechaDeVenta)
                                        .addComponent(lbMostrarFechaDeVenta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbIVA)
                                        .addComponent(lbMostrarIVA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) // Espacio pequeño (6px)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbTotal)
                                        .addComponent(lbMostrarTotal))

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGenerarPDF)
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String numFacturaStr = txtBuscar.getText().trim();
        if (numFacturaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, Mensajes.MSG_INGRESE_NUM_FACTURA, Mensajes.TITULO_ADVERTENCIA, JOptionPane.WARNING_MESSAGE);
            txtBuscar.requestFocus();
            return;
        }

        try {
            int numFactura = Integer.parseInt(numFacturaStr);
            
            if (numFactura <= 0) {
                JOptionPane.showMessageDialog(this, Mensajes.MSG_NUMERO_POSITIVO, Mensajes.TITULO_ADVERTENCIA, JOptionPane.WARNING_MESSAGE);
                txtBuscar.requestFocus();
                return;
            }
            
            ModeloReporteFactura comprobante = controlador.buscarComprobante(numFactura);
            
            if (comprobante != null) {
                reporteActual = comprobante;
                
                lbMostrarFactura.setText(String.valueOf(comprobante.getIdFactura()));
                lbMostrarFechaDeVenta.setText(comprobante.getFechaFactura().toString());
                lbMostrarNombres.setText(comprobante.getCliente().getNombre());
                lbMostrarApellidoPaterno.setText(comprobante.getCliente().getApPaterno());
                lbMostrarApellidoMaterno.setText(comprobante.getCliente().getApMaterno());
                
                modeloTablaProductos.setRowCount(0);
                for (ModeloDetalleVenta item : comprobante.getItems()) {
                    double total = (item.getSubtotal()*Constantes.TASA_IVA)+item.getSubtotal();
                    modeloTablaProductos.addRow(new Object[]{
                        item.getNombreProducto(),
                        item.getCantidad(),
                        item.getPrecioVenta(),
                        item.getSubtotal(),
                        total
                    });
                }
                
                lbMostrarIVA.setText(String.valueOf(comprobante.getIva()));
                lbMostrarTotal.setText(String.valueOf((comprobante.getTotal()*Constantes.TASA_IVA)+comprobante.getTotal()));
                
                btnGenerarPDF.setEnabled(true);
                
            } else {
                JOptionPane.showMessageDialog(this, Mensajes.MSG_FACTURA_NO_ENCONTRADA + numFactura, Mensajes.TITULO_ADVERTENCIA, JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, Mensajes.MSG_NUMERO_INVALIDO, Mensajes.TITULO_ERROR, JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, Mensajes.MSG_ERROR_BD + e.getMessage(), Mensajes.TITULO_ERROR, JOptionPane.ERROR_MESSAGE);
            limpiarCampos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        if (reporteActual == null) {
            JOptionPane.showMessageDialog(this,
                    Mensajes.MSG_REPORTE_REQUERIDO_PDF,
                    Mensajes.TITULO_ADVERTENCIA,
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String rutaPDF = GeneradorPDF.generarPDFReporteFactura(reporteActual);

            int respuesta = JOptionPane.showConfirmDialog(this,
                    String.format(Mensajes.MSG_PDF_GENERADO_EXITO, rutaPDF),
                    Mensajes.TITULO_PDF_GENERADO,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                abrirArchivo(rutaPDF);
            }

        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(this,
                    Mensajes.MSG_ERROR_CREAR_PDF + e.getMessage(),
                    Mensajes.TITULO_ERROR,
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    /**
     * Abre un archivo con la aplicación predeterminada del sistema.
     * 
     * @param rutaArchivo La ruta del archivo a abrir
     */
    private void abrirArchivo(String rutaArchivo) {
        try {
            File archivo = new File(rutaArchivo);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(archivo);
            } else {
                JOptionPane.showMessageDialog(this,
                        Mensajes.MSG_ERROR_ABRIR_ARCHIVO + "\nUbicación: " + rutaArchivo,
                    "Información", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                "Error al abrir el archivo: " + e.getMessage(),
                    Mensajes.TITULO_ERROR,
                JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbApellidoMaterno;
    private javax.swing.JLabel lbApellidoPaterno;
    private javax.swing.JLabel lbFactura;
    private javax.swing.JLabel lbFechaDeVenta;
    private javax.swing.JLabel lbIVA;
    private javax.swing.JLabel lbMostrarApellidoMaterno;
    private javax.swing.JLabel lbMostrarApellidoPaterno;
    private javax.swing.JLabel lbMostrarFactura;
    private javax.swing.JLabel lbMostrarFechaDeVenta;
    private javax.swing.JLabel lbMostrarIVA;
    private javax.swing.JLabel lbMostrarNombres;
    private javax.swing.JLabel lbMostrarTotal;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbProductos;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pnlDatosCliente;
    private javax.swing.JPanel pnlIngresarNumeroDeFactura;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

